# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[social.params]
icon = "brand-github"

[social.params]
icon = "brand-twitter"
